### ISSUE TITLE
引用报错  MiniProgramError

### ISSUE THREAD

**Issue by Magesss** [b5156/wxapp-computed#1]
我通过npm下载插件，在页面导入就一直报这个错误，我导入其他插件也会报这个错误，想问下这个错误是怎么回事呢？万分干感谢！！！
VM2277:1 MiniProgramError
module "node_modules/wxapp-computed/wxapp-computed" is not defined
Error: module "node_modules/wxapp-computed/wxapp-computed" is not defined
    at require (http://127.0.0.1:54524/appservice/__dev__/WAService.js:2:2053348)
    at http://127.0.0.1:54524/appservice/__dev__/WAService.js:2:2052954
    at http://127.0.0.1:54524/appservice/pages/class/class.js:4:22
    at require (http://127.0.0.1:54524/appservice/__dev__/WAService.js:2:2053581)
    at <anonymous>:245:7
    at doWhenAllScriptLoaded (http://127.0.0.1:54524/appservice/appservice?t=1593941790480:4252:21)
    at HTMLScriptElement.scriptLoaded (http://127.0.0.1:54524/appservice/appservice?t=1593941790480:4268:5)
    at HTMLScriptElement.script.onload (http://127.0.0.1:54524/appservice/appservice?t=1593941790480:4276:20)

**Comment by lbqdly** [comment]
像是项目没有找个这个包，你可以打印一下引入的变量是否符合预期
